apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cadereceita-com-tls
spec:
  secretName: cadereceita-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: cadereceita.com.br
  dnsNames:
    - cadereceita.com.br
    - www.cadereceita.com.br
    - sabre.cadereceita.com.br
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - cadereceita.com.br
          - www.cadereceita.com.br
          - sabre.cadereceita.com.br
