apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: donibtk/beta-sabre-server
          ports:
            - containerPort: 3000
          env:
            - name: SABRE_DATABASE_USERNAME
              value: postgres
            - name: SABRE_DATABASE_HOST
              value: postgres-cluster-ip-service
            - name: SABRE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgrespassword
                  key: POSTGRES_PASSWORD
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: railsmasterkey
                  key: RAILS_MASTER_KEY
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: googleapplicationcredentials
                  key: google_storage_key.txt
